### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by RamonGilabert** [iOS10-KIT/UI#15]

**Comment by RamonGilabert** [comment]
Leave this one to me please! :P

**Comment by cjmlgrto** [comment]
Website Tasks:
- [ ] Mockup
- [ ] Logo / Favicon (@cjmlgrto)
- [ ] Code (@RamonGilabert)
- [ ] Setup Domain / GitHub Pages (@RamonGilabert)

**Comment by RamonGilabert** [comment]
Being done here: https://github.com/RamonGilabert/UIWebsiteKit

Tomorrow afternoon the code begins. It should not take too long. After that I'll just buy a domain and put it in GitHub Pages. Should be fairly easy to do. I just need your magic icons! :)
