### ISSUE TITLE
Apple News Icon in the widget is incorrect

### ISSUE THREAD

**Issue by jordibruin** [iOS10-KIT/UI#25]
Right now it's two squares where in the real icon it's a scroll. Also the "N" in the logo doesn't match correctly.

I suggest we add a page with the high res icons for the new apps, which we can then reuse across the entire UI.

**Comment by cjmlgrto** [comment]
Aye, definitely! We'll need some help getting all the icons in.

**Comment by jordibruin** [comment]
I had some trouble getting the branches and pull requests going, but will work try it again next week.

**Comment by RamonGilabert** [comment]
Tried replicating it better:

<img width="281" alt="screen shot 2016-07-03 at 11 54 52 am" src="https://cloud.githubusercontent.com/assets/6138120/16544839/ff7831c8-4114-11e6-9da8-1287bf4513f7.png">
