### ISSUE TITLE
Issue with Repo: Pull Request Errors

### ISSUE THREAD

**Issue by cjmlgrto** [iOS10-KIT/UI#26]
A few people have reached out and they've told me they can't seem to submit pull requests or work with branches. 

Anyone else experiencing this issue? Not sure what's going on. Maybe it's a GitHub organisations/members/collaborators thing? 😕 cc: @RamonGilabert

**Comment by RamonGilabert** [comment]
Mmm. It might have to do with the fact that they have to do a fork first and then do the tutorial. I'll add it to the README.

It would be useful to see the error message that they get, but probably is that.

**Comment by RamonGilabert** [comment]
Added a more explanatory tutorial now:

https://github.com/iOS10-KIT/UI/blob/master/README.md

Let me know how it goes, @cjmlgrto.

**Comment by RamonGilabert** [comment]
I'll close the issue for now, feel free to reopen it if more people complain about some problems! :)
