### ISSUE TITLE
Love the theme of terminal in README, could you tell me the theme name?

### ISSUE THREAD

**Issue by viix** [iOS10-KIT/UI#27]
:), thanks, although not related.

**Comment by cjmlgrto** [comment]
It's a theme Ramon made! He's gonna release it sometime— so keep an eye out for it on Twitter. We'll also let you know when he release it. He's @RamonGilabert on there :)

**Comment by RamonGilabert** [comment]
Here it is y'all!

https://twitter.com/RamonGilabert/status/747065712376692736

**Comment by viix** [comment]
thanks~
