### ISSUE TITLE
Always export the artboards to be able to see the diffs on the Pull Requests

### ISSUE THREAD

**Issue by lanceplaine** [iOS10-KIT/UI#28]
Example:

<img width="1006" alt="screen shot 2016-06-23 at 9 06 30 am" src="https://cloud.githubusercontent.com/assets/5476205/16294606/cde88fd6-3921-11e6-9006-5ac46bcc3c69.png">

https://github.com/lanceplaine/capnet-pressing-design/pull/27/files

---

At work @Talentoday I use the same principles:
- Sketch files in the `sketch` folder
- Exported artboards in the `mockups` folder

**Comment by cjmlgrto** [comment]
This is really really good. I'll re-organise the folders as such, add it to the contribution guide.

**Comment by lanceplaine** [comment]
Great. Let me know if I can help. I can do one or two projects as example once Git LFS is set up
