### ISSUE TITLE
Add Git LFS

### ISSUE THREAD

**Issue by lanceplaine** [iOS10-KIT/UI#29]
Without [Git LFS](https://git-lfs.github.com) the repo is soon going to be too big to use if it's becoming popular

**Comment by cjmlgrto** [comment]
Awesome idea. I'll set this up over the weekend. Ping @RamonGilabert

**Comment by lanceplaine** [comment]
Note that you might want to do a push force on master the first time you set up Git LFS in order to remove all the `.sketch` binary from the history. Which is not a big deal since you're just starting the project. This way you'll have a lighter repo.

**Comment by RamonGilabert** [comment]
Good stuff! Added it to my todo list for the weekend! Having a crazy week! :)

Oh, saw that you are gonna do it, let's sync afterwards, @cjmlgrto! :)

**Comment by cjmlgrto** [comment]
Added.
