### ISSUE TITLE
Use the official iOS 10 wallpaper

### ISSUE THREAD

**Issue by ghost** [iOS10-KIT/UI#30]
I extracted the official iOS 10 wallpapers from the root file system, if you want to use it in the Sketch files instead of the current gradients. Use them if you would like a more accurate recreation: [iOS 10 Wallpapers.zip](https://github.com/iOS10-KIT/UI/files/332697/iOS.10.Wallpapers.zip)

**Comment by gregbarbosa** [comment]
@roonieone Question on that (without vearing too off topic), how did you extract them? I haven't been able to find them or get them off.

**Comment by ghost** [comment]
@gregbarbosa https://gist.github.com/roonieone/d6567e80500d1e3f6e5fa8e80d5d8b3c

**Comment by cjmlgrto** [comment]
Whoa, off-topic, but an awesome guide to extract 'em. Super cool Thank you!
