### ISSUE TITLE
Unable to open PNG files. 

### ISSUE THREAD

**Issue by wviana** [iOS10-KIT/UI#34]
Hello, I've been unable to open png files in macOS Preview app:

![screen shot 2016-06-29 at 09 35 27](https://cloud.githubusercontent.com/assets/1062631/16452046/d4946dd6-3ddc-11e6-8c9c-3fc31a48a4f1.png)

**Comment by lanceplaine** [comment]
Do you have Git LFS installed?
If not it's normal. Files are just pointers without LFS

**Comment by lanceplaine** [comment]
what is the size of your file?

**Comment by wviana** [comment]
No I don't, the only thing that I've done was download the project as zip to take a look at it.
Here is the files size:

![screen shot 2016-06-29 at 09 53 54](https://cloud.githubusercontent.com/assets/1062631/16452575/8e070754-3ddf-11e6-9070-dc36e365f2d6.png)

**Comment by lanceplaine** [comment]
Thanks @wviana for your feedback

Looks like it's a GitHub issue who doesn't handle well Git LFS yet on the download button.
https://github.com/github/git-lfs/issues/903

@cjmlgrto any idea on how to handle the issue so the button on the page http://puzzles.design can work?

**Comment by wviana** [comment]
@lanceplaine Should I try cloning the repository?
I already installed `git lfs` I'll try and give you feedback soon.

**Comment by lanceplaine** [comment]
If you do it will work.

But we need to find a solution to have the "Download" button work on the http://puzzles.design page because people who just want to get all the files and not contribute shouldn't have to install Git, Git LFS and clone the repo.

**Comment by cjmlgrto** [comment]
Indeed. I'm gonna upload a "v1.0" build, and link that version as the downloadable file.

**Comment by cjmlgrto** [comment]
Argh! This is not user-friendly. 😠 Since Git LFS is tracking .sketch, .png, .jpeg, etc— when users download the source zip, it's all just pointers!! (Not the full thing!)

**I'm going to disable Git LFS indefinitely.**

**Comment by lanceplaine** [comment]
Ok

**Comment by cjmlgrto** [comment]
I've just pulled it back to commit `17341f21801b7562d752d9142cf0a59c0d755c86`

It should work just as it did before. // Ping @RamonGilabert and @wviana

**Comment by wviana** [comment]
When cloning it was taking forever, When I interrupted I got a

> Warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'
> 
> Exiting because of "interrupt" signal.

**Comment by wviana** [comment]
@cjmlgrto Should I try to download the _zip_ again?

**Comment by wviana** [comment]
Worked as It suppose to. Thank you all for the attention. 👍🏻
